# Generated by Django 2.2.5 on 2019-11-20 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191120_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 14, 51, 36, 642784, tzinfo=utc)),
        ),
    ]
